{{- if and .Values.serviceMonitor.enabled .Values.enabledCollectors }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "state-metrics.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "state-metrics.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "state-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: server
      path: {{ .Values.config.server.metricsPath }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- if .Values.tls.enabled }}
      scheme: https
      tlsConfig:
        {{- if .Values.tls.insecureSkipVerify }}
        insecureSkipVerify: true
        {{- else }}
        caFile: /etc/prometheus/secrets/{{ include "state-metrics.fullname" . }}-tls/ca.crt
        {{- end }}
      {{- end }}
      {{- if .Values.auth.enabled }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
