{{- if and .Values.vmServiceScrape.enabled .Values.enabledCollectors }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "state-metrics.fullname" . }}
  {{- if .Values.vmServiceScrape.namespace }}
  namespace: {{ .Values.vmServiceScrape.namespace }}
  {{- end }}
  labels:
    {{- include "state-metrics.labels" . | nindent 4 }}
    {{- with .Values.vmServiceScrape.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "state-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.config.server.metricsPath }}
      interval: {{ .Values.vmServiceScrape.interval }}
      scrapeTimeout: {{ .Values.vmServiceScrape.scrapeTimeout }}
      {{- if .Values.tls.enabled }}
      scheme: https
      tlsConfig:
        {{- if .Values.tls.insecureSkipVerify }}
        insecureSkipVerify: true
        {{- else }}
        ca:
          secret:
            name: {{ include "state-metrics.fullname" . }}-tls
            key: ca.crt
        {{- end }}
      {{- end }}
      {{- if .Values.auth.enabled }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      {{- end }}
      {{- with .Values.vmServiceScrape.relabelConfigs }}
      relabelConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vmServiceScrape.metricRelabelConfigs }}
      metricRelabelConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
