{{- if and .Values.enabledCollectors .Values.auth.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sealos-state-metrics.fullname" . }}-metrics-reader
  labels:
    {{- include "sealos-state-metrics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sealos-state-metrics.fullname" . }}-metrics-reader
subjects:
{{- range .Values.auth.allowedServiceAccounts }}
- kind: ServiceAccount
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}
{{- end }}
