{{- if and .Values.enabledCollectors .Values.auth.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sealos-state-metrics.fullname" . }}-metrics-reader
  labels:
    {{- include "sealos-state-metrics.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - {{ .Values.config.server.metricsPath | quote }}
  verbs:
  - get
{{- end }}
